import 'package:securywallet/Api_Service/Apikey_Service.dart';
import 'package:securywallet/Screens/Previous_Home_Screen/Model/Asset_Model/Asset_Model.dart';

class CoinListConfig {
  static const int usdtDecimal = 2;
  static const int cryptoDecimal = 18;

  static List<Map<String, dynamic>> rawCoinList = [
    {
      "rpcURL": "",
      "explorerURL": "https://live.blockcypher.com/btc/",
      "coinSymbol": "BTC",
      "coinName": "Bitcoin",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1696501400",
      "balanceFetchAPI": "https://api.blockcypher.com/v1/btc/main/addrs/",
      "sendAmountAPI": "https://api.blockcypher.com/v1/btc/main/txs/new",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Bitcoin",
      "gasPriceSymbol": "BTC",
    },
    {
      "rpcURL": "",
      "explorerURL": "https://tronscan.org/#/",
      "coinSymbol": "TRX",
      "coinName": "TRON",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/128x128/1958.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "TRON",
      "gasPriceSymbol": "TRX",
    },
    {
      "rpcURL": "",
      "explorerURL": "https://solscan.io/",
      "coinSymbol": "SOL",
      "coinName": "Solana",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/4128/large/solana.png?1696504756",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Solana",
      "gasPriceSymbol": "SOL",
    },
    {
      "rpcURL": "",
      "explorerURL": "https://livenet.xrpl.org/",
      "coinSymbol": "XRP",
      "coinName": "XRP",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "XRP",
      "gasPriceSymbol": "XRP",
    },
    {
      // "rpcURL": "https://binance.llamarpc.com/",
      "rpcURL": "https://bsc-dataseed1.binance.org/",
      "explorerURL": "https://bscscan.com/",
      "coinSymbol": "BNB",
      "coinName": "BNB Smart Chain",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "BNB Smart Chain",
      "gasPriceSymbol": "BNB",
    },
    {
      "rpcURL": "https://mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://etherscan.io",
      "coinSymbol": "ETH",
      "coinName": "Ethereum",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/279/large/ethereum.png?1696501628",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Ethereum",
      "gasPriceSymbol": "ETH",
    },
    {
      "rpcURL":
          "https://avalanche-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://snowtrace.io/",
      "coinSymbol": "AVAX",
      "coinName": "Avalanche C-Chain",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Avalanche C-Chain",
      "gasPriceSymbol": "AVAX",
    },
    {
      "rpcURL":
          "https://arbitrum-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://explorer.arbitrum.io/",
      "coinSymbol": "ARB",
      "coinName": "Arbitrum One",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/16547/large/arb.jpg?1721358242",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Arbitrum One",
      "gasPriceSymbol": "ARB",
    },
    {
      "rpcURL": "https://celo-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://explorer.celo.org/mainnet/",
      "coinSymbol": "Celo",
      "coinName": "Celo",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/64x64/5567.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Celo",
      "gasPriceSymbol": "Celo",
    },
    {
      "rpcURL": "https://linea-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://lineascan.build/",
      "coinSymbol": "TBA",
      "coinName": "Linea",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/64x64/27657.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Linea",
      "gasPriceSymbol": "TBA",
    },
    {
      "rpcURL":
          "https://polygon-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://polygonscan.com/",
      "coinSymbol": "POL",
      "coinName": "Polygon",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/64x64/3890.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Polygon",
      "gasPriceSymbol": "POL",
    },
    {
      "rpcURL":
          "https://optimism-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://optimistic.etherscan.io/",
      "coinSymbol": "OP",
      "coinName": "Optimism",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/64x64/11840.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Optimism",
      "gasPriceSymbol": "OP",
    },
    {
      "rpcURL": "https://palm-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://etherscan.io/",
      "coinSymbol": "PALM",
      "coinName": "PaLM AI",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/64x64/28567.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "PaLM AI",
      "gasPriceSymbol": "PALM",
    },
    // {
    //   "rpcURL":
    //       "https://starknet-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
    //   "explorerURL": "https://starkscan.co/",
    //   "coinSymbol": "STRK",
    //   "coinName": "Starknet",
    //   "imageUrl":
    //       "https://s2.coinmarketcap.com/static/img/coins/64x64/22691.png",
    //   "balanceFetchAPI": "",
    //   "sendAmountAPI": "",
    //   "address": "",
    //   "coinType": "1",
    //   "tokenAddress": "",
    //   "tokenDecimal": "",
    //   "network": "Starknet",
    //   "gasPriceSymbol": "STRK",
    // },
    {
      "rpcURL": "https://cronos-evm-rpc.publicnode.com",
      "explorerURL": "https://cronoscan.com/",
      "coinSymbol": "CRO",
      "coinName": "Cronos",
      "imageUrl":
          "https://s3.coinmarketcap.com/static-gravity/image/84e1ec1257dd4a6da6ee5584338a2460.jpeg",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Cronos",
      "gasPriceSymbol": "Cronos",
    },
    {
      "rpcURL": "https://erpc.xdcrpc.com",
      "explorerURL": "https://xdcscan.com/",
      "coinSymbol": "XDC",
      "coinName": "XDC",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/200x200/2634.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "XDC",
      "gasPriceSymbol": "XDC",
    },
    {
      "rpcURL": "https://mantle-rpc.publicnode.com",
      "explorerURL": "https://explorer.mantle.xyz/",
      "coinSymbol": "MNT",
      "coinName": "Mantle",
      "imageUrl":
          "https://media.tenor.com/RcDul7MEWb0AAAAe/mantle-mantle-network.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Mantle",
      "gasPriceSymbol": "MNT",
    },
    {
      "rpcURL": "https://api.evm.eosnetwork.com",
      "explorerURL": "https://explorer.evm.eosnetwork.com/",
      "coinSymbol": "EOS",
      "coinName": "EOS",
      "imageUrl":
          "https://cdn4.vectorstock.com/i/1000x1000/91/18/crypto-coin-eos-icon-on-white-vector-20409118.jpg",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "EOS",
      "gasPriceSymbol": "EOS",
    },
    // {
    //   "rpcURL": "https://dappnode3.ont.io:10339",
    //   "explorerURL": "https://explorer.ont.io/",
    //   "coinSymbol": "ONT",
    //   "coinName": "Ontology",
    //   "imageUrl":
    //       "https://w7.pngwing.com/pngs/348/734/png-transparent-ontology-logo-ontology-symbol-ontology-sign-ontology-crypto-ontology-coin-ontology-3d-icon-thumbnail.png",
    //   "balanceFetchAPI": "",
    //   "sendAmountAPI": "",
    //   "address": "",
    //   "coinType": "1",
    //   "tokenAddress": "",
    //   "tokenDecimal": "",
    //   "network": "Ontology",
    //   "gasPriceSymbol": "ONT",
    // },
    // {
    //   "rpcURL": "https://rpc-mainnet.vechain.energy",
    //   "explorerURL": "https://explore.vechain.org/",
    //   "coinSymbol": "VET",
    //   "coinName": "VeChain",
    //   "imageUrl":
    //       "https://www.shutterstock.com/image-vector/vechain-vet-coin-icon-cryptocurrency-260nw-2111148341.jpg",
    //   "balanceFetchAPI": "",
    //   "sendAmountAPI": "",
    //   "address": "",
    //   "coinType": "3",
    //   "tokenAddress": "",
    //   "tokenDecimal": "",
    //   "network": "VeChain",
    //   "gasPriceSymbol": "VET",
    // },
    //---------------Testnet-------------------------------------------------
    // {
    //   "rpcURL": "https://rpc-testnet.vechain.energy",
    //   "explorerURL": "https://explore-testnet.vechain.org/",
    //   "coinSymbol": "tVET",
    //   "coinName": "tVeChain",
    //   "imageUrl":
    //       "https://www.shutterstock.com/image-vector/vechain-vet-coin-icon-cryptocurrency-260nw-2111148341.jpg",
    //   "balanceFetchAPI": "",
    //   "sendAmountAPI": "",
    //   "address": "",
    //   "coinType": "3",
    //   "tokenAddress": "",
    //   "tokenDecimal": "",
    //   "network": "Testnet",
    //   "gasPriceSymbol": "tVET",
    // },
    {
      "rpcURL": "",
      "explorerURL": "https://live.blockcypher.com/btc-testnet/",
      "coinSymbol": "tBTC",
      "coinName": "tBitcoin",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1696501400",
      "balanceFetchAPI": "https://api.blockcypher.com/v1/btc/test3/addrs/",
      "sendAmountAPI": "https://api.blockcypher.com/v1/btc/test3/txs/new",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tBTC",
    },
    {
      "rpcURL": "",
      "explorerURL": "https://solscan.io/",
      "coinSymbol": "tSOL",
      "coinName": "Solana Testnet",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/4128/large/solana.png?1696504756",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tSOL",
    },
    {
      "rpcURL": "",
      "explorerURL": "https://nile.tronscan.org/#/",
      "coinSymbol": "tTRX",
      "coinName": "TRON Testnet",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/128x128/1958.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tTRX",
    },
    {
      "rpcURL": "",
      "explorerURL": "https://testnet.xrpl.org/",
      "coinSymbol": "tXRP",
      "coinName": "XRP Testnet",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "3",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tXRP",
    },
    {
      "rpcURL": "https://sepolia.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://sepolia.etherscan.io/",
      "coinSymbol": "sepETH",
      "coinName": "Sepolia",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/279/large/ethereum.png?1696501628",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "sepETH",
    },

    {
      "rpcURL": "https://bsc-testnet-rpc.publicnode.com",
      "explorerURL": "https://testnet.bscscan.com/",
      "coinSymbol": "tBNB",
      "coinName": "BNB Testnet",
      "imageUrl":
          "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tBNB",
    },
    {
      "rpcURL":
          "https://celo-alfajores.infura.io/v3/${apiKeyService.infuraKey}",
      "explorerURL": "https://alfajores.celoscan.io/",
      "coinSymbol": "tCelo",
      "coinName": "Celo - Alfajores",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/64x64/5567.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tCelo",
    },
    {
      "rpcURL": "https://endpoints.omniatech.io/v1/cronos/testnet/public",
      "explorerURL": "https://explorer.cronos.org/testnet",
      "coinSymbol": "tCronos",
      "coinName": "tCronos",
      "imageUrl":
          "https://s3.coinmarketcap.com/static-gravity/image/84e1ec1257dd4a6da6ee5584338a2460.jpeg",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tCronos",
    },
    {
      "rpcURL": "https://erpc.apothem.network",
      "explorerURL": "https://testnet.xdcscan.com/",
      "coinSymbol": "tXDC",
      "coinName": "tXDC",
      "imageUrl":
          "https://s2.coinmarketcap.com/static/img/coins/200x200/2634.png",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tXDC",
    },
    // {
    //   "rpcURL": "https://polaris2.ont.io:10339",
    //   "explorerURL": "https://explorer.ont.io/testnet",
    //   "coinSymbol": "tONT",
    //   "coinName": "tOntology",
    //   "imageUrl":
    //       "https://w7.pngwing.com/pngs/348/734/png-transparent-ontology-logo-ontology-symbol-ontology-sign-ontology-crypto-ontology-coin-ontology-3d-icon-thumbnail.png",
    //   "balanceFetchAPI": "",
    //   "sendAmountAPI": "",
    //   "address": "",
    //   "coinType": "1",
    //   "tokenAddress": "",
    //   "tokenDecimal": "",
    //   "network": "Testnet",
    //   "gasPriceSymbol": "tONT",
    // },
    {
      "rpcURL": "https://api.testnet.evm.eosnetwork.com",
      "explorerURL": "https://explorer.testnet.evm.eosnetwork.com/",
      "coinSymbol": "tEOS",
      "coinName": "tEOS",
      "imageUrl":
          "https://cdn4.vectorstock.com/i/1000x1000/91/18/crypto-coin-eos-icon-on-white-vector-20409118.jpg",
      "balanceFetchAPI": "",
      "sendAmountAPI": "",
      "address": "",
      "coinType": "1",
      "tokenAddress": "",
      "tokenDecimal": "",
      "network": "Testnet",
      "gasPriceSymbol": "tEOS",
    },
  ];

  static List<AssetModel> get coinModelList =>
      rawCoinList.map((map) => AssetModel.fromJson(map)).toList();
}
