

import 'package:securywallet/Api_Service/Apikey_Service.dart';

List<Map<String, String>> mandatoryCoinList = [
  {
    "rpcURL": "https://www.nvxoscan.com/",
    "explorerURL": "https://nvxoexplorer.com/",
    "coinSymbol": "NVXO",
    "coinName": "NVXO Chain",
    "imageUrl":
        "https://firebasestorage.googleapis.com/v0/b/nvwallet-5ec7e.appspot.com/o/images%2FAsset%2064x.png?alt=media&token=1e803128-1a39-4bc0-8f32-abf2bca83263",
    "balanceFetchAPI": "",
    "sendAmountAPI": "",
    "address": "",
    "coinType": "1",
    "tokenAddress": "",
    "tokenDecimal": "",
    "network": "NVXO Chain",
    "gasPriceSymbol": "NVXO",
  },
  {
    "rpcURL": "https://binance.llamarpc.com/",
    "explorerURL": "https://bscscan.com/",
    "coinSymbol": "BNB",
    "coinName": "BNB Smart Chain",
    "imageUrl":
        "https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970",
    "balanceFetchAPI": "",
    "sendAmountAPI": "",
    "address": "",
    "coinType": "1",
    "tokenAddress": "",
    "tokenDecimal": "",
    "network": "BNB Smart Chain",
    "gasPriceSymbol": "BNB",
  },
  {
    "rpcURL": "https://mainnet.infura.io/v3/${apiKeyService.infuraKey}",
    "explorerURL": "https://etherscan.io",
    "coinSymbol": "ETH",
    "coinName": "Ethereum",
    "imageUrl":
        "https://firebasestorage.googleapis.com/v0/b/icrypt-8cc00.appspot.com/o/eth.png?alt=media&token=2b5cd89e-3ece-45f9-8d12-b6cbe1d2a6a9",
    "balanceFetchAPI": "",
    "sendAmountAPI": "",
    "address": "",
    "coinType": "1",
    "tokenAddress": "",
    "tokenDecimal": "",
    "network": "Ethereum",
    "gasPriceSymbol": "ETH",
  },
  {
    "rpcURL":
        "https://avalanche-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
    "explorerURL": "https://snowtrace.io/",
    "coinSymbol": "AVAX",
    "coinName": "Avalanche C-Chain",
    "imageUrl":
        "https://firebasestorage.googleapis.com/v0/b/icrypt-8cc00.appspot.com/o/avax.png?alt=media&token=bd1e6e2b-044e-485a-95a8-a783b88a8a64",
    "balanceFetchAPI": "",
    "sendAmountAPI": "",
    "address": "",
    "coinType": "1",
    "tokenAddress": "",
    "tokenDecimal": "",
    "network": "Avalanche C-Chain",
    "gasPriceSymbol": "AVAX",
  },
  {
    "rpcURL":
        "https://arbitrum-mainnet.infura.io/v3/${apiKeyService.infuraKey}",
    "explorerURL": "https://explorer.arbitrum.io/",
    "coinSymbol": "ARB",
    "coinName": "Arbitrum One",
    "imageUrl":
        "https://firebasestorage.googleapis.com/v0/b/icrypt-8cc00.appspot.com/o/arbit.png?alt=media&token=fd37a38c-00c0-4cc1-a054-52fef89ea678",
    "balanceFetchAPI": "",
    "sendAmountAPI": "",
    "address": "",
    "coinType": "1",
    "tokenAddress": "",
    "tokenDecimal": "",
    "network": "Arbitrum One",
    "gasPriceSymbol": "ARB",
  },
  // {
  //   "rpcURL": "https://sepolia.infura.io/v3/${apiKeyService.infuraKey}",
  //   "explorerURL": "https://sepolia.etherscan.io/",
  //   "coinSymbol": "sepETH",
  //   "coinName": "Sepolia",
  //   "imageUrl":
  //       "https://firebasestorage.googleapis.com/v0/b/icrypt-8cc00.appspot.com/o/eth.png?alt=media&token=2b5cd89e-3ece-45f9-8d12-b6cbe1d2a6a9",
  //   "balanceFetchAPI": "",
  //   "sendAmountAPI": "",
  //   "address": "",
  //   "coinType": "1",
  //   "tokenAddress": "",
  //   "tokenDecimal": "",
  //   "network": "Testnet",
  //   "gasPriceSymbol": "sepETH",
  // },
  // {
  //   "rpcURL": "",
  //   "explorerURL": "https://tronscan.org/#/",
  //   "coinSymbol": "TRX",
  //   "coinName": "TRON",
  //   "imageUrl":
  //       "https://s2.coinmarketcap.com/static/img/coins/128x128/1958.png",
  //   "balanceFetchAPI": "",
  //   "sendAmountAPI": "",
  //   "address": "",
  //   "coinType": "3",
  //   "tokenAddress": "",
  //   "tokenDecimal": "",
  //   "network": "TRON",
  //   "gasPriceSymbol": "TRX",
  // },
  // {
  //   "rpcURL": "",
  //   "explorerURL": "https://solscan.io/",
  //   "coinSymbol": "SOL",
  //   "coinName": "Solana",
  //   "imageUrl":
  //       "https://assets.coingecko.com/coins/images/4128/large/solana.png?1696504756",
  //   "balanceFetchAPI": "",
  //   "sendAmountAPI": "",
  //   "address": "",
  //   "coinType": "3",
  //   "tokenAddress": "",
  //   "tokenDecimal": "",
  //   "network": "Solana",
  //   "gasPriceSymbol": "SOL",
  // },
];
