name: securywallet
description: "Securely manage your crypto wallets"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.1+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # Packages for wallet connect
  # ios scanner
  #  scan: ^1.6.0
  # Android Scanner
  mobile_scanner: ^6.0.2
  #  web3dart: ^2.3.0
  #  shared_preferences: ^2.0.7
  eth_sig_util: ^0.0.3
  json_annotation: ^4.7.0
  #  bip39: ^1.0.6
  #  bip32: ^2.0.0
  wallet_connect_dart_v2: ^0.0.1
  #  http: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  get: ^4.6.6
  get_storage: ^2.1.1
  connectivity_plus: ^6.0.5
  #  sizer: ^3.0.4
  http: ^1.1.0
  dots_indicator: ^3.0.0
  curved_navigation_bar: ^1.0.3
  local_auth: ^2.1.0
  clipboard: ^0.1.3
  #  bip39: ^1.0.6
  #  bip32: ^2.0.0
  web3dart: ^2.7.3
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
#  qr_code_scanner: ^1.0.1
  #  web_browser: ^0.7.4
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  qr_flutter: ^4.1.0
  flutter_gif: ^0.0.4
  xrpl: ^0.0.9

  share_plus: ^10.0.2
  image: ^4.2.0
  #  flutter_windowmanager: ^0.2.0
  flutter_windowmanager_plus: ^1.0.0
  #  flutter_barcode_scanner: ^2.0.0
  #  mobile_scanner: ^5.2.3
  #  terra_dart_sdk: ^1.0.2
  decimal: ^2.3.3
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.5
  web_socket_channel: ^2.4.0
  flutter_slidable: ^3.0.1
  emoji_picker_flutter: ^3.0.0
  encrypt: ^5.0.3
  tuple: ^2.0.2
  crypto: ^3.0.3
  webview_flutter: ^4.7.0
  #  wallet: ^0.0.13
  image_picker: ^1.0.8
  #  bitcoin_base: ^4.1.0
  #  bdk_flutter: ^0.30.0
  flutter_bitcoin: ^1.0.1
  json_bigint: ^3.1.0
  #  bs58check: ^1.0.2
  #  hex: ^0.2.0
  #  on_chain: ^4.2.0
  solana_web3: ^0.1.3
  solana_wallet: ^0.0.4
  base58check: ^2.0.0
  bs58: ^1.0.2
  ed25519_hd_key: ^2.3.0
  bech32: ^0.2.2
  tonutils: ^0.5.7
  #  cosmos_sdk: ^1.3.0
  #  terra_sdk_test: ^1.0.2
  #  terra_dart: ^1.0.0
  #  polkadot_dart: ^1.1.0
  #  polkadart: ^0.4.4
  #  substrate_bip39: ^0.4.0
  xrpl_dart: 5.4.0
  dart_jsonwebtoken: ^2.14.1
  cryptography: ^2.7.0
  in_app_review: ^2.0.9
  ton: ^0.0.4

  #FireBaseDetails
  googleapis_auth:
  googleapis:
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^17.2.2
  ton_dart: ^0.1.4
  catalyst_cardano: ^0.4.1
  catalyst_key_derivation: ^0.1.3
  sha3: ^0.2.0
  bitcoin_base: ^4.9.4
  thor_request_dart: ^1.1.0
  fluttertoast: ^8.0.9
  permission_handler: ^11.1.0
  video_player: ^2.10.0
  chewie: ^1.13.0
#  on_chain: ^7.0.0



dependency_overrides:
  http: ^0.13.5
  connectivity_plus: ^6.1.0
  #  share_plus: ^6.3.1
  blockchain_utils: ^4.2.0



  pinenacl: ^0.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg
    - assets/Images/
    #      - assets/Icons/
    - assets/JsonFile/
    - assets/GIF/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    - family: LexendDeca
      fonts:
        - asset: assets/AppFonts/LexendDeca-Black.ttf
          weight: 400
        - asset: assets/AppFonts/LexendDeca-Bold.ttf
          weight: 100
        - asset: assets/AppFonts/LexendDeca-ExtraBold.ttf
          weight: 500
        - asset: assets/AppFonts/LexendDeca-ExtraLight.ttf
          weight: 600
        - asset: assets/AppFonts/LexendDeca-Light.ttf
          weight: 700
        - asset: assets/AppFonts/LexendDeca-Medium.ttf
          weight: 300
        - asset: assets/AppFonts/LexendDeca-Regular.ttf
          weight: 200
        - asset: assets/AppFonts/LexendDeca-Thin.ttf
          weight: 800
        - asset: assets/AppFonts/LexendDeca-SemiBold.ttf
          weight: 900
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
