// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRLCHaU3E_XWavX4Q_cb_o0j52i9c1hu4',
    appId: '1:651647208375:web:dd7b24039319095934b632',
    messagingSenderId: '651647208375',
    projectId: 'nvwallet-5ec7e',
    authDomain: 'nvwallet-5ec7e.firebaseapp.com',
    storageBucket: 'nvwallet-5ec7e.appspot.com',
    measurementId: 'G-XTEFHP1T0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByn31m8jGczNj1IuUJLGEBsFa4tlJVs5Q',
    appId: '1:651647208375:android:d701e0d1a535fe7634b632',
    messagingSenderId: '651647208375',
    projectId: 'nvwallet-5ec7e',
    storageBucket: 'nvwallet-5ec7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8Xc0ENVIP_iWinypbAdXbvTuuKs3nu0',
    appId: '1:651647208375:ios:34cd73bff51086e834b632',
    messagingSenderId: '651647208375',
    projectId: 'nvwallet-5ec7e',
    storageBucket: 'nvwallet-5ec7e.appspot.com',
    iosBundleId: 'com.nvwallet.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8Xc0ENVIP_iWinypbAdXbvTuuKs3nu0',
    appId: '1:651647208375:ios:34cd73bff51086e834b632',
    messagingSenderId: '651647208375',
    projectId: 'nvwallet-5ec7e',
    storageBucket: 'nvwallet-5ec7e.appspot.com',
    iosBundleId: 'com.nvwallet.wallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRLCHaU3E_XWavX4Q_cb_o0j52i9c1hu4',
    appId: '1:651647208375:web:976608ebda70428f34b632',
    messagingSenderId: '651647208375',
    projectId: 'nvwallet-5ec7e',
    authDomain: 'nvwallet-5ec7e.firebaseapp.com',
    storageBucket: 'nvwallet-5ec7e.appspot.com',
    measurementId: 'G-WK576QG1XS',
  );
}
